export interface GalleryItem {
  id: string;
  title: string;
  category: "wedding" | "pre-wedding" | "birthday" | "couple";
  aspect: "portrait" | "landscape" | "square";
  width: number;
  height: number;
  src: string;
  alt: string;
  story?: string;
  featured?: boolean;
}

export const galleryCategories = [
  { id: "all", label: "All Stories" },
  { id: "wedding", label: "Wedding" },
  { id: "pre-wedding", label: "Pre-Wedding" },
  { id: "couple", label: "Couple & Romance" },
  { id: "birthday", label: "Milestones & Birthday" },
] as const;

export const galleryItems: GalleryItem[] = [
  {
    id: "wedding-pixel-pros-wedding-13",
    title: "Cathedral Altar Vows Ceremony",
    category: "wedding",
    aspect: "landscape",
    width: 1080,
    height: 720,
    src: "/images/pixel-pros/wedding/pixel-pros-wedding-13.webp",
    alt: "Pixel Pros wedding photography \u2014 Cathedral Altar Vows Ceremony",
    story: "Grand wide angle view of the couple before the church altar.",
    featured: true,
  },
  {
    id: "couple-pixel-pros-couple-01",
    title: "Ethereal Water Reflections Portrait",
    category: "couple",
    aspect: "portrait",
    width: 1440,
    height: 1800,
    src: "/images/pixel-pros/couple/pixel-pros-couple-01.webp",
    alt: "Pixel Pros couple photography \u2014 Ethereal Water Reflections Portrait",
    story: "High-fashion couple floating on calm lake with glass-like reflections.",
    featured: true,
  },
  {
    id: "prewedding-pixel-pros-pre-wedding-02",
    title: "Dilkush Lake Tranquility",
    category: "pre-wedding",
    aspect: "portrait",
    width: 1440,
    height: 1800,
    src: "/images/pixel-pros/pre-wedding/pixel-pros-pre-wedding-02.webp",
    alt: "Pixel Pros pre-wedding photography \u2014 Dilkush Lake Tranquility",
    story: "Quiet moment in traditional wooden boat with misty mountain backdrop.",
    featured: true,
  },
  {
    id: "birthday-pixel-pros-birthday-01",
    title: "Kasavu Attire Milestone by Lotus Pond",
    category: "birthday",
    aspect: "portrait",
    width: 1080,
    height: 1350,
    src: "/images/pixel-pros/birthday/pixel-pros-birthday-01.webp",
    alt: "Pixel Pros birthday photography \u2014 Kasavu Attire Milestone by Lotus Pond",
    story: "Traditional Kerala Kasavu portrait with lotus flowers beside serene pond.",
    featured: true,
  },
  {
    id: "portrait-pixel-pros-portrait-01",
    title: "Radiant Christian Bride in White",
    category: "wedding",
    aspect: "portrait",
    width: 1440,
    height: 1800,
    src: "/images/pixel-pros/portrait/pixel-pros-portrait-01.webp",
    alt: "Pixel Pros photography of radiant christian bride in white",
    story: "Graceful bridal portrait in layered white gown and delicate veil.",
    featured: true,
  },
  {
    id: "couple-pixel-pros-couple-14",
    title: "Sunlit Meadow Picnic Reverie",
    category: "couple",
    aspect: "landscape",
    width: 1440,
    height: 960,
    src: "/images/pixel-pros/couple/pixel-pros-couple-14.webp",
    alt: "Pixel Pros couple photography \u2014 Sunlit Meadow Picnic Reverie",
    story: "Intimate golden hour picnic celebration in lush nature.",
    featured: true,
  },
  {
    id: "prewedding-pixel-pros-pre-wedding-05",
    title: "DREAMY Love Meadow Stroll",
    category: "pre-wedding",
    aspect: "portrait",
    width: 1440,
    height: 1800,
    src: "/images/pixel-pros/pre-wedding/pixel-pros-pre-wedding-05.webp",
    alt: "Pixel Pros pre-wedding photography \u2014 DREAMY Love Meadow Stroll",
    story: "Carefree walk across wild green coastal hills under gentle sky.",
    featured: true,
  },
  {
    id: "wedding-pixel-pros-wedding-04",
    title: "Team Bride & Groomsmen Celebration",
    category: "wedding",
    aspect: "portrait",
    width: 1440,
    height: 1800,
    src: "/images/pixel-pros/wedding/pixel-pros-wedding-04.webp",
    alt: "Pixel Pros wedding photography \u2014 Team Bride & Groomsmen Celebration",
    story: "Joyous celebration with bridesmaids and groomsmen in matching green suits.",
    featured: true,
  },
  {
    id: "birthday-pixel-pros-birthday-03",
    title: "Beach Horizon Parents & Child",
    category: "birthday",
    aspect: "portrait",
    width: 1440,
    height: 1800,
    src: "/images/pixel-pros/birthday/pixel-pros-birthday-03.webp",
    alt: "Pixel Pros birthday photography \u2014 Beach Horizon Parents & Child",
    story: "Minimalist high-key portrait of parents lifting their child against open sky.",
    featured: true,
  },
  {
    id: "wedding-pixel-pros-wedding-12",
    title: "Fine Art Bride in Quiet Prayer",
    category: "wedding",
    aspect: "landscape",
    width: 1080,
    height: 720,
    src: "/images/pixel-pros/wedding/pixel-pros-wedding-12.webp",
    alt: "Pixel Pros wedding photography \u2014 Fine Art Bride in Quiet Prayer",
    story: "Fine art black and white capture of bride holding white flower bouquet.",
    featured: true,
  },
  {
    id: "portrait-pixel-pros-portrait-04",
    title: "Valentine\u2019s Intimate Warmth",
    category: "couple",
    aspect: "portrait",
    width: 1440,
    height: 1800,
    src: "/images/pixel-pros/portrait/pixel-pros-portrait-04.webp",
    alt: "Pixel Pros photography of valentine\u2019s intimate warmth",
    story: "Close-up fine art portrait with warm sumi tones and gentle gaze.",
    featured: true,
  },
  {
    id: "prewedding-pixel-pros-pre-wedding-06",
    title: "Joyous Haldi Ceremony Celebrations",
    category: "pre-wedding",
    aspect: "portrait",
    width: 1440,
    height: 1800,
    src: "/images/pixel-pros/pre-wedding/pixel-pros-pre-wedding-06.webp",
    alt: "Pixel Pros pre-wedding photography \u2014 Joyous Haldi Ceremony Celebrations",
    story: "Vibrant family celebration with marigold petals and yellow attire.",
    featured: false,
  },
  {
    id: "birthday-pixel-pros-birthday-02",
    title: "First Birthday Innocence in White",
    category: "birthday",
    aspect: "portrait",
    width: 1440,
    height: 1800,
    src: "/images/pixel-pros/birthday/pixel-pros-birthday-02.webp",
    alt: "Pixel Pros birthday photography \u2014 First Birthday Innocence in White",
    story: "One-year-old child in silver-white gown sitting among lush green foliage.",
    featured: true,
  },
  {
    id: "wedding-pixel-pros-wedding-05",
    title: "My World Soul Vintage Scooter Story",
    category: "wedding",
    aspect: "portrait",
    width: 1440,
    height: 1800,
    src: "/images/pixel-pros/wedding/pixel-pros-wedding-05.webp",
    alt: "Pixel Pros wedding photography \u2014 My World Soul Vintage Scooter Story",
    story: "Vintage Vespa outdoor portrait amidst misty rolling hills.",
    featured: true,
  },
  {
    id: "couple-pixel-pros-couple-03",
    title: "Moody Twilight By The Lake",
    category: "couple",
    aspect: "portrait",
    width: 1440,
    height: 1800,
    src: "/images/pixel-pros/couple/pixel-pros-couple-03.webp",
    alt: "Pixel Pros couple photography \u2014 Moody Twilight By The Lake",
    story: "Deep tones and quiet romance as evening descends.",
    featured: false,
  },
  {
    id: "wedding-pixel-pros-wedding-14",
    title: "Modern Architectural Reception Look",
    category: "wedding",
    aspect: "landscape",
    width: 1080,
    height: 720,
    src: "/images/pixel-pros/wedding/pixel-pros-wedding-14.webp",
    alt: "Pixel Pros wedding photography \u2014 Modern Architectural Reception Look",
    story: "Couple poised on architectural glass staircase in reception attire.",
    featured: false,
  },
  {
    id: "portrait-pixel-pros-portrait-02",
    title: "South Indian Muhurtham Bride",
    category: "wedding",
    aspect: "portrait",
    width: 1440,
    height: 1800,
    src: "/images/pixel-pros/portrait/pixel-pros-portrait-02.webp",
    alt: "Pixel Pros photography of south indian muhurtham bride",
    story: "Traditional bride adorned in heirloom temple jewelry and silk saree.",
    featured: false,
  },
  {
    id: "couple-pixel-pros-couple-04",
    title: "Picnic Laughter in Natural Light",
    category: "couple",
    aspect: "portrait",
    width: 1440,
    height: 1800,
    src: "/images/pixel-pros/couple/pixel-pros-couple-04.webp",
    alt: "Pixel Pros couple photography \u2014 Picnic Laughter in Natural Light",
    story: "Natural unposed laughter during relaxed outdoor afternoon.",
    featured: false,
  },
  {
    id: "prewedding-pixel-pros-pre-wedding-03",
    title: "Kerala Kasavu Terracotta Spread",
    category: "pre-wedding",
    aspect: "portrait",
    width: 1440,
    height: 1800,
    src: "/images/pixel-pros/pre-wedding/pixel-pros-pre-wedding-03.webp",
    alt: "Pixel Pros pre-wedding photography \u2014 Kerala Kasavu Terracotta Spread",
    story: "Editorial spread in handwoven cream kasavu attire and jasmine garland.",
    featured: false,
  },
  {
    id: "birthday-pixel-pros-birthday-04",
    title: "Temple Steps Lotus Ceremony",
    category: "birthday",
    aspect: "portrait",
    width: 1080,
    height: 1350,
    src: "/images/pixel-pros/birthday/pixel-pros-birthday-04.webp",
    alt: "Pixel Pros birthday photography \u2014 Temple Steps Lotus Ceremony",
    story: "Traditional celebration portrait with handcrafted jewelry.",
    featured: false,
  },
  {
    id: "portrait-pixel-pros-portrait-03",
    title: "Moody Groom Pre-Ceremony Portrait",
    category: "wedding",
    aspect: "portrait",
    width: 1440,
    height: 1800,
    src: "/images/pixel-pros/portrait/pixel-pros-portrait-03.webp",
    alt: "Pixel Pros photography of moody groom pre-ceremony portrait",
    story: "Reflective quiet portrait of the groom before taking the stage.",
    featured: false,
  },
  {
    id: "couple-pixel-pros-couple-05",
    title: "Quiet Summer Toast",
    category: "couple",
    aspect: "portrait",
    width: 1440,
    height: 1800,
    src: "/images/pixel-pros/couple/pixel-pros-couple-05.webp",
    alt: "Pixel Pros couple photography \u2014 Quiet Summer Toast",
    story: "Intimate picnic moments with fruit basket and sparkling glasses.",
    featured: false,
  },
  {
    id: "prewedding-pixel-pros-pre-wedding-04",
    title: "Locomotive & Railway Tracks Narrative",
    category: "pre-wedding",
    aspect: "portrait",
    width: 1440,
    height: 1800,
    src: "/images/pixel-pros/pre-wedding/pixel-pros-pre-wedding-04.webp",
    alt: "Pixel Pros pre-wedding photography \u2014 Locomotive & Railway Tracks Narrative",
    story: "Cinematic couple journey on open railway tracks.",
    featured: false,
  },
  {
    id: "birthday-pixel-pros-birthday-05",
    title: "Sunny Milestone Smiles",
    category: "birthday",
    aspect: "portrait",
    width: 1080,
    height: 1350,
    src: "/images/pixel-pros/birthday/pixel-pros-birthday-05.webp",
    alt: "Pixel Pros birthday photography \u2014 Sunny Milestone Smiles",
    story: "Bright natural light smiles celebrating family milestones.",
    featured: false,
  },
  {
    id: "wedding-pixel-pros-wedding-03",
    title: "Traditional South Indian Couple Portrait",
    category: "wedding",
    aspect: "portrait",
    width: 1440,
    height: 1800,
    src: "/images/pixel-pros/wedding/pixel-pros-wedding-03.webp",
    alt: "Pixel Pros wedding photography \u2014 Traditional South Indian Couple Portrait",
    story: "Regal couple portrait in ceremonial South Indian silk attire.",
    featured: false,
  },
  {
    id: "couple-pixel-pros-couple-06",
    title: "Playful Greenery Embrace",
    category: "couple",
    aspect: "portrait",
    width: 1440,
    height: 1800,
    src: "/images/pixel-pros/couple/pixel-pros-couple-06.webp",
    alt: "Pixel Pros couple photography \u2014 Playful Greenery Embrace",
    story: "Warm embrace surrounded by verdant leaves and soft light.",
    featured: false,
  },
  {
    id: "prewedding-pixel-pros-pre-wedding-07",
    title: "Outdoor Wine Toast in Nature",
    category: "pre-wedding",
    aspect: "portrait",
    width: 1440,
    height: 1800,
    src: "/images/pixel-pros/pre-wedding/pixel-pros-pre-wedding-07.webp",
    alt: "Pixel Pros pre-wedding photography \u2014 Outdoor Wine Toast in Nature",
    story: "Relaxed couple toast amidst lush natural foliage.",
    featured: false,
  },
  {
    id: "birthday-pixel-pros-birthday-06",
    title: "Birthday Party Ambient Decor",
    category: "birthday",
    aspect: "portrait",
    width: 1080,
    height: 1350,
    src: "/images/pixel-pros/birthday/pixel-pros-birthday-06.webp",
    alt: "Pixel Pros birthday photography \u2014 Birthday Party Ambient Decor",
    story: "Artistic documentation of celebration balloons, lights, and decor.",
    featured: false,
  },
  {
    id: "wedding-pixel-pros-wedding-06",
    title: "Church Altar Sacred Exchange",
    category: "wedding",
    aspect: "portrait",
    width: 1440,
    height: 1800,
    src: "/images/pixel-pros/wedding/pixel-pros-wedding-06.webp",
    alt: "Pixel Pros wedding photography \u2014 Church Altar Sacred Exchange",
    story: "The solemn exchange of vows in sacred church architecture.",
    featured: false,
  },
  {
    id: "couple-pixel-pros-couple-07",
    title: "Dramatic Twilight Silhouette",
    category: "couple",
    aspect: "portrait",
    width: 1440,
    height: 1800,
    src: "/images/pixel-pros/couple/pixel-pros-couple-07.webp",
    alt: "Pixel Pros couple photography \u2014 Dramatic Twilight Silhouette",
    story: "Striking evening portraiture with dramatic rim lighting.",
    featured: false,
  },
  {
    id: "prewedding-pixel-pros-pre-wedding-08",
    title: "Coastal Breeze Candid Laughter",
    category: "pre-wedding",
    aspect: "portrait",
    width: 1440,
    height: 1800,
    src: "/images/pixel-pros/pre-wedding/pixel-pros-pre-wedding-08.webp",
    alt: "Pixel Pros pre-wedding photography \u2014 Coastal Breeze Candid Laughter",
    story: "Spontaneous smiles caught during unhurried outdoor session.",
    featured: false,
  },
  {
    id: "birthday-pixel-pros-birthday-07",
    title: "Joyful Cake Cutting Laughs",
    category: "birthday",
    aspect: "portrait",
    width: 1080,
    height: 1350,
    src: "/images/pixel-pros/birthday/pixel-pros-birthday-07.webp",
    alt: "Pixel Pros birthday photography \u2014 Joyful Cake Cutting Laughs",
    story: "Spontaneous laughter during milestone cake-cutting ceremony.",
    featured: false,
  },
  {
    id: "wedding-pixel-pros-wedding-07",
    title: "Candid Marriage Ritual Glimpse",
    category: "wedding",
    aspect: "portrait",
    width: 1440,
    height: 1800,
    src: "/images/pixel-pros/wedding/pixel-pros-wedding-07.webp",
    alt: "Pixel Pros wedding photography \u2014 Candid Marriage Ritual Glimpse",
    story: "Spontaneous tender glance captured during wedding ceremonies.",
    featured: false,
  },
  {
    id: "couple-pixel-pros-couple-08",
    title: "Gentle Forehead Kiss",
    category: "couple",
    aspect: "portrait",
    width: 1080,
    height: 1350,
    src: "/images/pixel-pros/couple/pixel-pros-couple-08.webp",
    alt: "Pixel Pros couple photography \u2014 Gentle Forehead Kiss",
    story: "Tender forehead kiss with soft warm flare.",
    featured: false,
  },
  {
    id: "prewedding-pixel-pros-pre-wedding-09",
    title: "Palm Grove Sunset Silhouette",
    category: "pre-wedding",
    aspect: "portrait",
    width: 1080,
    height: 1350,
    src: "/images/pixel-pros/pre-wedding/pixel-pros-pre-wedding-09.webp",
    alt: "Pixel Pros pre-wedding photography \u2014 Palm Grove Sunset Silhouette",
    story: "Warm amber silhouette against towering coconut palms.",
    featured: false,
  },
  {
    id: "birthday-pixel-pros-birthday-08",
    title: "Family in Pure White",
    category: "birthday",
    aspect: "portrait",
    width: 1440,
    height: 1800,
    src: "/images/pixel-pros/birthday/pixel-pros-birthday-08.webp",
    alt: "Pixel Pros birthday photography \u2014 Family in Pure White",
    story: "Harmonious family portrait in crisp white attire.",
    featured: false,
  },
  {
    id: "wedding-pixel-pros-wedding-08",
    title: "Joyful Bridal Entry & Petals",
    category: "wedding",
    aspect: "portrait",
    width: 1440,
    height: 1800,
    src: "/images/pixel-pros/wedding/pixel-pros-wedding-08.webp",
    alt: "Pixel Pros wedding photography \u2014 Joyful Bridal Entry & Petals",
    story: "A glowing bridal walk flanked by blessings and flower petals.",
    featured: false,
  },
  {
    id: "couple-pixel-pros-couple-09",
    title: "Modern Lifestyle Duo",
    category: "couple",
    aspect: "portrait",
    width: 1080,
    height: 1350,
    src: "/images/pixel-pros/couple/pixel-pros-couple-09.webp",
    alt: "Pixel Pros couple photography \u2014 Modern Lifestyle Duo",
    story: "Contemporary portraiture celebrating honest young love.",
    featured: false,
  },
  {
    id: "prewedding-pixel-pros-pre-wedding-10",
    title: "Nature\u2019s Quiet Embrace",
    category: "pre-wedding",
    aspect: "portrait",
    width: 1080,
    height: 1350,
    src: "/images/pixel-pros/pre-wedding/pixel-pros-pre-wedding-10.webp",
    alt: "Pixel Pros pre-wedding photography \u2014 Nature\u2019s Quiet Embrace",
    story: "Intimate couple embrace framed by dense forest canopy.",
    featured: false,
  },
  {
    id: "birthday-pixel-pros-birthday-09",
    title: "Loving Parent & Child Embrace",
    category: "birthday",
    aspect: "portrait",
    width: 1440,
    height: 1800,
    src: "/images/pixel-pros/birthday/pixel-pros-birthday-09.webp",
    alt: "Pixel Pros birthday photography \u2014 Loving Parent & Child Embrace",
    story: "Tender moment of parental warmth and pure connection.",
    featured: false,
  },
  {
    id: "wedding-pixel-pros-wedding-09",
    title: "Fairy Lights Evening Reception",
    category: "wedding",
    aspect: "portrait",
    width: 1440,
    height: 1800,
    src: "/images/pixel-pros/wedding/pixel-pros-wedding-09.webp",
    alt: "Pixel Pros wedding photography \u2014 Fairy Lights Evening Reception",
    story: "Intimate evening couple portrait surrounded by sparkling fairy lights.",
    featured: false,
  },
  {
    id: "couple-pixel-pros-couple-10",
    title: "Dawn Reverie in South India",
    category: "couple",
    aspect: "portrait",
    width: 1440,
    height: 1800,
    src: "/images/pixel-pros/couple/pixel-pros-couple-10.webp",
    alt: "Pixel Pros couple photography \u2014 Dawn Reverie in South India",
    story: "Peaceful morning light casting a soft glow over couple.",
    featured: false,
  },
  {
    id: "prewedding-pixel-pros-pre-wedding-11",
    title: "Morning Sunlight Connection",
    category: "pre-wedding",
    aspect: "portrait",
    width: 1440,
    height: 1800,
    src: "/images/pixel-pros/pre-wedding/pixel-pros-pre-wedding-11.webp",
    alt: "Pixel Pros pre-wedding photography \u2014 Morning Sunlight Connection",
    story: "Warm morning rays filtering through trees as couple walks together.",
    featured: false,
  },
  {
    id: "birthday-pixel-pros-birthday-10",
    title: "Sunshine & Child Laughter",
    category: "birthday",
    aspect: "portrait",
    width: 1440,
    height: 1800,
    src: "/images/pixel-pros/birthday/pixel-pros-birthday-10.webp",
    alt: "Pixel Pros birthday photography \u2014 Sunshine & Child Laughter",
    story: "Candid childhood laughter captured in natural daylight.",
    featured: false,
  },
  {
    id: "wedding-pixel-pros-wedding-10",
    title: "Ceremonial Silk Elegance",
    category: "wedding",
    aspect: "portrait",
    width: 1440,
    height: 1800,
    src: "/images/pixel-pros/wedding/pixel-pros-wedding-10.webp",
    alt: "Pixel Pros wedding photography \u2014 Ceremonial Silk Elegance",
    story: "Classic stance in authentic South Indian ceremonial attire.",
    featured: false,
  },
  {
    id: "couple-pixel-pros-couple-11",
    title: "Golden Meadow Walk",
    category: "couple",
    aspect: "portrait",
    width: 1152,
    height: 1440,
    src: "/images/pixel-pros/couple/pixel-pros-couple-11.webp",
    alt: "Pixel Pros couple photography \u2014 Golden Meadow Walk",
    story: "Golden sunset illumination as couple walks hand in hand.",
    featured: false,
  },
  {
    id: "birthday-pixel-pros-birthday-11",
    title: "Family Togetherness Joy",
    category: "birthday",
    aspect: "portrait",
    width: 1440,
    height: 1800,
    src: "/images/pixel-pros/birthday/pixel-pros-birthday-11.webp",
    alt: "Pixel Pros birthday photography \u2014 Family Togetherness Joy",
    story: "Three generations celebrating together with genuine smiles.",
    featured: false,
  },
  {
    id: "wedding-pixel-pros-wedding-11",
    title: "Bridal Henna & Gold Details",
    category: "wedding",
    aspect: "portrait",
    width: 1080,
    height: 1350,
    src: "/images/pixel-pros/wedding/pixel-pros-wedding-11.webp",
    alt: "Pixel Pros wedding photography \u2014 Bridal Henna & Gold Details",
    story: "Intricate mehndi artistry and gold bangles captured with macro clarity.",
    featured: false,
  },
  {
    id: "couple-pixel-pros-couple-12",
    title: "Misty Water Reflection",
    category: "couple",
    aspect: "portrait",
    width: 1440,
    height: 1800,
    src: "/images/pixel-pros/couple/pixel-pros-couple-12.webp",
    alt: "Pixel Pros couple photography \u2014 Misty Water Reflection",
    story: "Atmospheric reflection on still mountain lake.",
    featured: false,
  },
  {
    id: "birthday-pixel-pros-birthday-12",
    title: "Pure Wonder Milestone",
    category: "birthday",
    aspect: "portrait",
    width: 1440,
    height: 1800,
    src: "/images/pixel-pros/birthday/pixel-pros-birthday-12.webp",
    alt: "Pixel Pros birthday photography \u2014 Pure Wonder Milestone",
    story: "Child\u2019s wide-eyed wonder exploring the world.",
    featured: false,
  },
  {
    id: "couple-pixel-pros-couple-13",
    title: "Unhurried Coastal Connection",
    category: "couple",
    aspect: "portrait",
    width: 1440,
    height: 1800,
    src: "/images/pixel-pros/couple/pixel-pros-couple-13.webp",
    alt: "Pixel Pros couple photography \u2014 Unhurried Coastal Connection",
    story: "Honest smiles with authentic emotion in natural coastal light.",
    featured: false,
  },
  {
    id: "birthday-pixel-pros-birthday-13",
    title: "Beach Play Steps",
    category: "birthday",
    aspect: "portrait",
    width: 1440,
    height: 1800,
    src: "/images/pixel-pros/birthday/pixel-pros-birthday-13.webp",
    alt: "Pixel Pros birthday photography \u2014 Beach Play Steps",
    story: "Candid running on warm sand during sunset.",
    featured: false,
  },
  {
    id: "birthday-pixel-pros-birthday-14",
    title: "Garden First Birthday Portrait",
    category: "birthday",
    aspect: "portrait",
    width: 1440,
    height: 1800,
    src: "/images/pixel-pros/birthday/pixel-pros-birthday-14.webp",
    alt: "Pixel Pros birthday photography \u2014 Garden First Birthday Portrait",
    story: "Adorable first birthday memories captured in garden setting.",
    featured: false,
  },
  {
    id: "birthday-pixel-pros-birthday-15",
    title: "Curious Eyes Milestone",
    category: "birthday",
    aspect: "portrait",
    width: 1440,
    height: 1800,
    src: "/images/pixel-pros/birthday/pixel-pros-birthday-15.webp",
    alt: "Pixel Pros birthday photography \u2014 Curious Eyes Milestone",
    story: "Expressive close-up capturing authentic childhood charm.",
    featured: false,
  },
  {
    id: "birthday-pixel-pros-birthday-16",
    title: "Festive Gathering Atmosphere",
    category: "birthday",
    aspect: "portrait",
    width: 1440,
    height: 1800,
    src: "/images/pixel-pros/birthday/pixel-pros-birthday-16.webp",
    alt: "Pixel Pros birthday photography \u2014 Festive Gathering Atmosphere",
    story: "Colorful energy of family and friends celebrating.",
    featured: false,
  },
  {
    id: "birthday-pixel-pros-birthday-17",
    title: "Celebration Warmth",
    category: "birthday",
    aspect: "portrait",
    width: 1440,
    height: 1800,
    src: "/images/pixel-pros/birthday/pixel-pros-birthday-17.webp",
    alt: "Pixel Pros birthday photography \u2014 Celebration Warmth",
    story: "Warm hugs and congratulations from loved ones.",
    featured: false,
  },
  {
    id: "birthday-pixel-pros-birthday-18",
    title: "Dusk Cuddle Moments",
    category: "birthday",
    aspect: "portrait",
    width: 1440,
    height: 1800,
    src: "/images/pixel-pros/birthday/pixel-pros-birthday-18.webp",
    alt: "Pixel Pros birthday photography \u2014 Dusk Cuddle Moments",
    story: "Quiet moment of rest between mother and baby at twilight.",
    featured: false,
  },
  {
    id: "birthday-pixel-pros-birthday-19",
    title: "Generations of Love",
    category: "birthday",
    aspect: "portrait",
    width: 1440,
    height: 1800,
    src: "/images/pixel-pros/birthday/pixel-pros-birthday-19.webp",
    alt: "Pixel Pros birthday photography \u2014 Generations of Love",
    story: "Heirloom family photograph to be cherished across years.",
    featured: false,
  },
];
